
services:
  nginx:
    image: arm64v8/nginx:latest
    ports:
      - "443:80"
    volumes:
      - ./app/public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fastcgi-php.conf:/etc/nginx/fastcgi-php.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - DB_DATABASE=ex_db
      - DB_USERNAME=user
      - DB_PASSWORD=test
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: ex_db
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
    - "5433:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  node:
    build:
      context: node
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  mysql_data:
